channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fasttext=0.9.2
  - gensim=4.1.2
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - google-auth=2.12.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - jieba=0.42.1
  - matplotlib=3.6.0
  - matplotlib-base=3.6.0
  - numpy=1.22.1
  - pandas=1.4.4
  - pip=22.3
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python-xxhash=3.0.0
  - python_abi=3.10
  - pytz=2022.2.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - scipy=1.8.0
  - tk=8.6.12
  - yaml=0.2.5
  - pip:
    - chardet==3.0.4
    - googletrans==4.0.0rc1
    - h11==0.9.0
    - h2==3.2.0
    - hpack==3.0.0
    - hstspreload==2022.10.1
    - httpcore==0.9.1
    - httpx==0.13.3
    - hyperframe==5.2.0
    - idna==2.10
    - rfc3986==1.5.0
    - scikit-learn==1.1.2
    - sniffio==1.3.0
    - stopwordsiso==0.6.1
